//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchLSI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\..\\generate.m")]
        public string generatePATH {
            get {
                return ((string)(this["generatePATH"]));
            }
            set {
                this["generatePATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Octave\\Octave-4.2.1\\bin\\octave-cli.exe")]
        public string octavePATH {
            get {
                return ((string)(this["octavePATH"]));
            }
            set {
                this["octavePATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Cyws\\Dropbox\\2.letnik\\MatematicnoModeliranje\\1.projekt\\search.m")]
        public string searchPATH {
            get {
                return ((string)(this["searchPATH"]));
            }
            set {
                this["searchPATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Cyws\\Dropbox\\2.letnik\\MatematicnoModeliranje\\1.projekt\\classic\\")]
        public string folderPATH {
            get {
                return ((string)(this["folderPATH"]));
            }
            set {
                this["folderPATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Cyws\\Dropbox\\2.letnik\\MatematicnoModeliranje\\1.projekt\\")]
        public string matrixPATH {
            get {
                return ((string)(this["matrixPATH"]));
            }
            set {
                this["matrixPATH"] = value;
            }
        }
    }
}
